# Generated by Django 4.2.27 on 2026-01-28 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset', models.CharField(choices=[('web', 'web'), ('redes', 'redes'), ('ecommerce', 'ecommerce')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('processed_files', models.PositiveIntegerField(default=0)),
                ('result_zip', models.FileField(blank=True, null=True, upload_to='zips/')),
            ],
        ),
        migrations.CreateModel(
            name='JobFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='originals/')),
                ('original_name', models.CharField(max_length=255)),
                ('original_size', models.PositiveIntegerField()),
                ('output_file', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('output_name', models.CharField(blank=True, max_length=255)),
                ('output_size', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='jobs.job')),
            ],
        ),
    ]
