# Generated by Django 4.2.27 on 2026-01-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_appsettings_and_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAUSED', 'Paused'), ('CANCELED', 'Canceled'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
